meta:
  schema-version: 0.1.0
  created-on: "2025-12-31T10:35:41Z"
  cli-version: 0.2.0
projects:
  DB331106249C2F96C57D6B6EB0AD8940308AE637:
    targets:
      - pom.xml
    manager:
      ecosystem: java
      name: maven
      version: ""
    overrides:
      org.springframework:spring-beans:
        3.0.6.RELEASE:
          use: 3.0.6.RELEASE+sp1
      commons-beanutils:commons-beanutils:
        1.9.4:
          use: 1.9.4+sp1
      org.lz4:lz4-java:
        1.8.0:
          use: 1.8.0+sp1
